# Generated by Django 5.1.1 on 2024-09-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='ans_id',
            field=models.CharField(editable=False, max_length=7, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='ques_id',
            field=models.CharField(editable=False, max_length=7, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_id',
            field=models.CharField(editable=False, max_length=7, primary_key=True, serialize=False, unique=True),
        ),
    ]
