# Generated by Django 5.1.1 on 2024-09-29 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybud', '0002_alter_answers_ans_id_alter_questions_ques_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studybud.users'),
        ),
    ]
