# Generated by Django 5.1.1 on 2024-09-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybud', '0004_alter_quiz_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
